# Generated by Django 6.0 on 2025-12-15 15:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mark', models.CharField(max_length=55, verbose_name='Марка авто')),
                ('model', models.CharField(max_length=55, verbose_name='Модель авто')),
                ('color', models.CharField(max_length=25, verbose_name='Колір авто')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2050)], verbose_name='Рік випуску')),
                ('vin_code', models.CharField(max_length=55, unique=True, verbose_name='VIN номер авто')),
                ('license_plate', models.CharField(max_length=8, verbose_name='Номерний знак авто')),
                ('fuel_type', models.CharField(blank=True, choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], max_length=20, null=True, verbose_name='Тип пального')),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Await', 'Await'), ('Processing', 'Processing'), ('Service', 'Service')], default='Active', max_length=20, null=True, verbose_name='Статус авто')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробіг авто')),
                ('drive_type', models.CharField(blank=True, choices=[('FWD', 'Передній'), ('RWD', 'Задній'), ('AWD', 'Повний (AWD)'), ('4WD', 'Повний (4WD)')], max_length=55, null=True, verbose_name='Привід авто')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='car_photos/', verbose_name='Фото авто')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('message_type', models.CharField(max_length=55)),
                ('send_at', models.DateTimeField()),
                ('delivered_at', models.DateTimeField()),
                ('is_sended', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutlayAmount',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_per_item', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна за одиницю (PLN)')),
                ('item_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кількість')),
                ('full_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=32, verbose_name='Імя')),
                ('last_name', models.CharField(max_length=32, verbose_name='Призвіще')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='Пошта')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер телефону')),
                ('telegram_link', models.CharField(max_length=255, verbose_name='Посилання на телеграм')),
                ('is_active_telegram', models.BooleanField(default=False, verbose_name='Активований телеграм')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=32, verbose_name='Імя')),
                ('last_name', models.CharField(max_length=32, verbose_name='Призвіще')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='Пошта')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер телефону')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('auto_manager', 'Manager'), ('finance_manager', 'Finance')], default='customer', max_length=20, verbose_name='Роль користувача')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Верифікована пошта')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='В останнє залогінено')),
                ('is_active', models.BooleanField(default=True, help_text='Дозволити користувачу вхід в обліковий запис. Якщо False користувач буде заблокований', verbose_name='Активувати користувача')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='car_photos/')),
                ('order', models.IntegerField(default=0, help_text='Порядок відображення фото')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.car')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('file_path', models.CharField(max_length=255)),
                ('invoice_data', models.JSONField(default=dict)),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_archived', models.BooleanField(default=False)),
                ('cars', models.ManyToManyField(related_name='invoices', to='core.car')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('type', models.CharField(max_length=55)),
                ('count', models.IntegerField()),
                ('price_per_one', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_expenses', to='core.car')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Outlay',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('service', 'Сервіс'), ('other', 'Інші')], default='other', max_length=20, verbose_name='Тип витрати')),
                ('category', models.CharField(blank=True, choices=[('fuel', 'Паливо'), ('parts', 'Запчастини'), ('documents', 'Документи'), ('another', 'Інше')], default='fuel', max_length=20, null=True, verbose_name='Підкатегорія')),
                ('category_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Власна підкатегорія')),
                ('service_name', models.CharField(blank=True, max_length=55, null=True, verbose_name='Назва сервісу')),
                ('description', models.TextField(verbose_name='Опис')),
                ('cars', models.ManyToManyField(related_name='outlay_cars', to='core.car')),
                ('amount', models.ForeignKey(db_column='amount_id', on_delete=django.db.models.deletion.PROTECT, to='core.outlayamount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='core.owner', verbose_name='Власник авто'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(max_length=255)),
                ('social_media', models.CharField(blank=True, max_length=55)),
                ('has_social_media', models.BooleanField(default=False)),
                ('cars', models.ManyToManyField(related_name='services', to='core.car')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('name', models.CharField(max_length=55)),
                ('count', models.IntegerField()),
                ('price_per_one', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_expenses', to='core.car')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_services', to='core.service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
