# Generated by Django 6.0 on 2025-12-15 17:30

from django.db import migrations, models


def populate_name_from_description(apps, schema_editor):
    """Populate name field from description for existing records"""
    Outlay = apps.get_model('core', 'Outlay')
    for outlay in Outlay.objects.all():
        if outlay.description and not outlay.name:
            # Use first 255 characters of description as name
            outlay.name = outlay.description[:255]
            outlay.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlay',
            name='comment',
            field=models.TextField(blank=True, help_text='Додаткова інформація про витрату', null=True, verbose_name='Коментар'),
        ),
        migrations.AddField(
            model_name='outlay',
            name='name',
            field=models.CharField(default='', help_text='Коротка назва витрати для швидкої ідентифікації', max_length=255, verbose_name='Назва витрати'),
        ),
        migrations.RunPython(populate_name_from_description, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='outlay',
            name='description',
            field=models.TextField(blank=True, help_text="Залишено для сумісності, використовуйте 'Назва витрати' та 'Коментар'", null=True, verbose_name='Опис'),
        ),
    ]
