# Generated by Django 6.0 on 2025-12-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_outlay_name_and_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlay',
            name='name',
            field=models.CharField(blank=True, default='', help_text="Коротка назва витрати для швидкої ідентифікації (обов'язково для сервісу)", max_length=255, null=True, verbose_name='Назва витрати'),
        ),
    ]
