# Generated by Django 6.0 on 2025-12-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_outlayamount_price_per_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlayamount',
            name='item_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кількість'),
        ),
    ]
