# Generated by Django 6.0 on 2025-12-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
