# Generated by Django 6.0 on 2025-12-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_make_outlay_name_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlay',
            name='category',
            field=models.CharField(blank=True, choices=[('fuel', 'Паливо'), ('parts', 'Запчастини'), ('documents', 'Документи'), ('another', 'Інше')], default=None, max_length=20, null=True, verbose_name='Підкатегорія'),
        ),
    ]
