# Generated by Django 6.0 on 2025-12-15 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_category_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name', '-created_at']},
        ),
    ]
