# Generated by Django 6.0 on 2025-12-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="statuse",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Active", "Active"),
                    ("Await", "Awaite"),
                    ("Processing", "Processing"),
                    ("Service", "Service"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
