# Generated by Django 6.0 on 2025-12-15 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_service_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['last_name', 'first_name', '-created_at']},
        ),
    ]
