# Generated by Django 6.0 on 2025-12-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_owner_ordering'),
    ]

    operations = [
        # First, migrate existing data - convert Processing and Service to Active
        migrations.RunSQL(
            sql="UPDATE core_car SET status = 'Active' WHERE status IN ('Processing', 'Service');",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='car',
            name='drive_type',
            field=models.CharField(blank=True, choices=[('FWD', 'Передній'), ('RWD', 'Задній'), ('AWD', 'Повний'), ('4WD', 'Повний')], max_length=55, null=True, verbose_name='Привід авто'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Електричний'), ('hybrid', 'Гібридний')], max_length=20, null=True, verbose_name='Тип пального'),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Активне авто'), ('Await', 'Очікуюче авто')], default='Active', max_length=20, null=True, verbose_name='Статус авто'),
        ),
    ]
