# Generated by Django 6.0 on 2025-12-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='license_plate',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
