# Generated by Django 6.0 on 2025-12-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_update_car_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='drive_type',
            field=models.CharField(blank=True, choices=[('FWD', 'Передній'), ('RWD', 'Задній'), ('AWD', 'Повний')], max_length=55, null=True, verbose_name='Привід авто'),
        ),
    ]
