# Generated by Django 6.0 on 2025-12-24 20:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_car_drive_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tg_chat_id', models.IntegerField(editable=False, help_text='ID чату в Telegram', unique=True, verbose_name='Чат айді телеграма')),
                ('user_first', models.CharField(max_length=32, verbose_name='Імя ТГ користувача')),
                ('user_last', models.CharField(max_length=32, verbose_name='Призвіще')),
                ('tagname', models.CharField(max_length=32, unique=True, verbose_name='tag користувача телеграм')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tg_message_id', models.IntegerField(verbose_name='ID повідомлення з телеграма')),
                ('sender', models.CharField(choices=[('web', 'Web'), ('telegram', 'Telegram')], max_length=10)),
                ('text', models.TextField()),
                ('sended', models.BooleanField(default=False, verbose_name='Чи повідомлення доставлено користувачу')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('image', models.ImageField(upload_to='chat/images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.message')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
