# Generated by Django 6.0 on 2025-12-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_chat_message_messageimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='tg_chat_id',
            field=models.IntegerField(help_text='ID чату в Telegram', unique=True, verbose_name='Чат айді телеграма'),
        ),
    ]
