# Generated by Django 6.0 on 2026-01-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notificationservice_serviceeventschema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carservicestate',
            name='mileage',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
