# Generated by Django 6.0 on 2025-12-12 12:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_car_statuse"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="statuse",
            new_name="status",
        ),
    ]
