# Generated by Django 6.0 on 2025-12-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_chat_tg_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='contain_file',
            field=models.BooleanField(default=False, help_text='Файл, фото, документ', verbose_name='Містить вкладення'),
        ),
    ]
