# Generated by Django 6.0 on 2026-01-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_carservicestate_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефону'),
        ),
    ]
