# Generated by Django 6.0 on 2025-12-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_remove_invoice_expense_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="drive_type",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
