# Generated by Django 6.0 on 2025-12-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_message_contain_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='tg_message_id',
            field=models.BigIntegerField(verbose_name='ID повідомлення з телеграма'),
        ),
    ]
