# Generated by Django 6.0 on 2025-12-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_message_tg_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='tg_message_id',
            field=models.CharField(max_length=16, verbose_name='ID повідомлення з телеграма'),
        ),
    ]
