# Generated by Django 6.0 on 2025-12-13 19:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_car_drive_type"),
    ]

    operations = [
        # is_social_media вже було видалено в попередніх міграціях
        migrations.RunSQL(
            sql="ALTER TABLE core_service DROP COLUMN IF EXISTS is_social_media;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name="CarPhoto",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("photo", models.ImageField(upload_to="car_photos/")),
                ("order", models.IntegerField(default=0, help_text="Порядок відображення фото")),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="core.car",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
    ]
