# Generated by Django 6.0 on 2026-01-08 14:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_serviceevent_comment_serviceevent_interval_km_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Фактура', 'verbose_name_plural': 'Фактури'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=20, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='Назва товару')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Кількість')),
                ('price_netto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна нетто')),
                ('price_netto2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна нетто 2')),
                ('tax_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ПДВ %')),
                ('tax_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сума ПДВ')),
                ('price_brutto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна брутто')),
                ('current_car_vin', models.CharField(blank=True, max_length=55, null=True, verbose_name='VIN автомобіля')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.invoice')),
            ],
            options={
                'verbose_name': 'Позиція фактури',
                'verbose_name_plural': 'Позиції фактури',
                'ordering': ['item_id'],
            },
        ),
    ]
