# Generated by Django 6.0 on 2025-12-14 00:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_remove_service_is_social_media_carphoto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notifications",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("message", models.TextField()),
                ("message_type", models.CharField(max_length=55)),
                ("send_at", models.DateTimeField()),
                ("delivered_at", models.DateTimeField()),
                ("is_sended", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        # is_social_media was already removed in previous migrations (0011, 0013)
        # Using RunSQL to safely handle the case where it might not exist
        migrations.RunSQL(
            sql="ALTER TABLE core_service DROP COLUMN IF EXISTS is_social_media;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name="car",
            name="is_saved",
            field=models.BooleanField(default=False),
        ),
        # has_social_media was already added in migration 0011 using RunSQL
        # We need to update Django's state without modifying the database
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Database already has the column, so this is a no-op
                migrations.RunSQL(
                    sql="ALTER TABLE core_service ADD COLUMN IF NOT EXISTS has_social_media BOOLEAN DEFAULT FALSE;",
                    reverse_sql="ALTER TABLE core_service DROP COLUMN IF EXISTS has_social_media;",
                ),
            ],
            state_operations=[
                # Update Django's migration state to reflect that has_social_media exists
                migrations.AddField(
                    model_name="service",
                    name="has_social_media",
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
    ]
