# Generated by Django 6.0 on 2025-12-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_message_tg_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='tg_chat_id',
            field=models.BigIntegerField(help_text='ID чату в Telegram', unique=True, verbose_name='Чат айді телеграма'),
        ),
        migrations.AlterField(
            model_name='message',
            name='tg_message_id',
            field=models.BigIntegerField(verbose_name='ID повідомлення з телеграма'),
        ),
    ]
