# Generated by Django 6.0 on 2026-01-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_invoice_options_alter_invoice_invoice_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='item_name',
            field=models.CharField(max_length=1000, verbose_name='Назва товару'),
        ),
    ]
