# Generated by Django 6.0 on 2025-12-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_chat_tg_chat_id_alter_message_tg_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='user_last',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Призвіще'),
        ),
    ]
