# Generated by Django 6.0 on 2025-12-28 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_chat_user_last'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read_at',
        ),
    ]
