# Generated by Django 6.0 on 2025-12-28 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_message_read_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='message',
        ),
    ]
