# Generated by Django 6.0 on 2025-12-28 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_text_message_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='tg_message_id',
        ),
    ]
